[2017-09-27 21:39:53] request.INFO: Matched route "open_course_manage_teachers". {"route_parameters":{"_controller":"AppBundle\\Controller\\OpenCourseManageController::teachersAction","_permission":[],"id":"1","_route":"open_course_manage_teachers"},"request_uri":"http://172.17.0.3/app.php/open/course/1/manage/teachers"} []
[2017-09-27 21:39:53] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-27 21:39:53] security.DEBUG: User was reloaded from a user provider. {"username":"admin@admin.admin","provider":"Biz\\User\\UserProvider"} []
[2017-09-27 21:40:33] request.CRITICAL: Uncaught PHP Exception Biz\CloudPlatform\Client\CloudAPIIOException: "Connect api server timeout (url: http://leafapi1.edusoho.net/v1/lives/capacity?timestamp=1506519593)." at /var/www/html/src/Biz/CloudPlatform/Client/AbstractCloudAPI.php line 174 {"exception":"[object] (Biz\\CloudPlatform\\Client\\CloudAPIIOException(code: 0): Connect api server timeout (url: http://leafapi1.edusoho.net/v1/lives/capacity?timestamp=1506519593). at /var/www/html/src/Biz/CloudPlatform/Client/AbstractCloudAPI.php:174)"} []
[2017-09-27 21:40:33] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-14 19:16:57] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-04-14 19:16:58] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-04-14 19:17:29] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-04-14 19:17:29] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-04-14 19:18:56] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-04-14 19:18:56] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-04-14 19:19:17] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-04-14 19:19:17] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-04-14 19:22:08] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-04-14 19:22:09] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-04-14 19:22:19] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-04-14 19:22:19] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /var/www/html/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-04-14 21:42:54] request.INFO: Matched route "course_activity_download". {"route_parameters":{"_controller":"AppBundle\\Controller\\Activity\\DownloadController::downloadFileAction","_permission":[],"courseId":"1","activityId":"1","_route":"course_activity_download"},"request_uri":"http://127.0.0.1/course/1/activiy/1/download"} []
[2018-04-14 21:42:54] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-14 21:42:54] security.DEBUG: User was reloaded from a user provider. {"username":"teacher@teacher.teacher","provider":"Biz\\User\\UserProvider"} []
[2018-04-14 21:42:54] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "activity not found" at /var/www/html/src/AppBundle/Listener/ExceptionListener.php line 98 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): activity not found at /var/www/html/src/AppBundle/Listener/ExceptionListener.php:98, Codeages\\Biz\\Framework\\Service\\Exception\\NotFoundException(code: 0): activity not found at /var/www/html/src/Biz/BaseService.php:123)"} []
[2018-04-14 21:42:55] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-14 21:43:24] request.INFO: Matched route "course_activity_download". {"route_parameters":{"_controller":"AppBundle\\Controller\\Activity\\DownloadController::downloadFileAction","_permission":[],"courseId":"1","activityId":"1","_route":"course_activity_download"},"request_uri":"http://127.0.0.1/course/1/activiy/1/download"} []
[2018-04-14 21:43:24] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-14 21:43:24] security.DEBUG: User was reloaded from a user provider. {"username":"teacher@teacher.teacher","provider":"Biz\\User\\UserProvider"} []
[2018-04-14 21:43:24] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "activity not found" at /var/www/html/src/AppBundle/Listener/ExceptionListener.php line 98 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): activity not found at /var/www/html/src/AppBundle/Listener/ExceptionListener.php:98, Codeages\\Biz\\Framework\\Service\\Exception\\NotFoundException(code: 0): activity not found at /var/www/html/src/Biz/BaseService.php:123)"} []
[2018-04-14 21:43:24] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-14 21:43:33] request.INFO: Matched route "course_activity_download". {"route_parameters":{"_controller":"AppBundle\\Controller\\Activity\\DownloadController::downloadFileAction","_permission":[],"courseId":"1","activityId":"1","_route":"course_activity_download"},"request_uri":"http://127.0.0.1/course/1/activiy/1/download"} []
[2018-04-14 21:43:33] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-14 21:43:33] security.DEBUG: User was reloaded from a user provider. {"username":"teacher@teacher.teacher","provider":"Biz\\User\\UserProvider"} []
[2018-04-14 21:43:34] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "activity not found" at /var/www/html/src/AppBundle/Listener/ExceptionListener.php line 98 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): activity not found at /var/www/html/src/AppBundle/Listener/ExceptionListener.php:98, Codeages\\Biz\\Framework\\Service\\Exception\\NotFoundException(code: 0): activity not found at /var/www/html/src/Biz/BaseService.php:123)"} []
[2018-04-14 21:43:34] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-14 21:44:11] request.INFO: Matched route "admin". {"route_parameters":{"_controller":"CustomBundle\\Controller\\Admin\\DefaultController::indexAction","_route":"admin","_permission":[]},"request_uri":"http://192.168.43.215/admin/"} []
[2018-04-14 21:44:11] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-14 21:44:11] security.DEBUG: User was reloaded from a user provider. {"username":"1@1.com","provider":"Biz\\User\\UserProvider"} []
[2018-04-14 21:44:11] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2018-04-14 21:44:11] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php:119, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2018-04-14 21:44:12] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-14 21:44:31] request.INFO: Matched route "course_activity_download". {"route_parameters":{"_controller":"AppBundle\\Controller\\Activity\\DownloadController::downloadFileAction","_permission":[],"courseId":"1","activityId":"1","_route":"course_activity_download"},"request_uri":"http://127.0.0.1/course/1/activiy/1/download"} []
[2018-04-14 21:44:31] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-14 21:44:31] security.DEBUG: User was reloaded from a user provider. {"username":"teacher@teacher.teacher","provider":"Biz\\User\\UserProvider"} []
[2018-04-14 21:44:31] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "activity not found" at /var/www/html/src/AppBundle/Listener/ExceptionListener.php line 98 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): activity not found at /var/www/html/src/AppBundle/Listener/ExceptionListener.php:98, Codeages\\Biz\\Framework\\Service\\Exception\\NotFoundException(code: 0): activity not found at /var/www/html/src/Biz/BaseService.php:123)"} []
[2018-04-14 21:44:31] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-14 21:44:54] request.INFO: Matched route "course_activity_download". {"route_parameters":{"_controller":"AppBundle\\Controller\\Activity\\DownloadController::downloadFileAction","_permission":[],"courseId":"1","activityId":"1","_route":"course_activity_download"},"request_uri":"http://127.0.0.1/course/1/activiy/1/download?materialId=aaa"} []
[2018-04-14 21:44:54] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-14 21:44:54] security.DEBUG: User was reloaded from a user provider. {"username":"teacher@teacher.teacher","provider":"Biz\\User\\UserProvider"} []
[2018-04-14 21:44:54] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "activity not found" at /var/www/html/src/AppBundle/Listener/ExceptionListener.php line 98 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): activity not found at /var/www/html/src/AppBundle/Listener/ExceptionListener.php:98, Codeages\\Biz\\Framework\\Service\\Exception\\NotFoundException(code: 0): activity not found at /var/www/html/src/Biz/BaseService.php:123)"} []
[2018-04-14 21:44:55] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-14 21:45:38] request.INFO: Matched route "course_activity_download". {"route_parameters":{"_controller":"AppBundle\\Controller\\Activity\\DownloadController::downloadFileAction","_permission":[],"courseId":"1","activityId":"1","_route":"course_activity_download"},"request_uri":"http://127.0.0.1/course/1/activiy/1/download?materialId=aaa"} []
[2018-04-14 21:45:38] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-14 21:45:38] security.DEBUG: User was reloaded from a user provider. {"username":"teacher@teacher.teacher","provider":"Biz\\User\\UserProvider"} []
[2018-04-14 21:45:39] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "activity not found" at /var/www/html/src/AppBundle/Listener/ExceptionListener.php line 98 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): activity not found at /var/www/html/src/AppBundle/Listener/ExceptionListener.php:98, Codeages\\Biz\\Framework\\Service\\Exception\\NotFoundException(code: 0): activity not found at /var/www/html/src/Biz/BaseService.php:123)"} []
[2018-04-14 21:45:39] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-14 21:45:54] request.INFO: Matched route "course_activity_download". {"route_parameters":{"_controller":"AppBundle\\Controller\\Activity\\DownloadController::downloadFileAction","_permission":[],"courseId":"1","activityId":"1","_route":"course_activity_download"},"request_uri":"http://127.0.0.1/course/1/activiy/1/download?materialId=aaa"} []
[2018-04-14 21:45:54] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-14 21:45:54] security.DEBUG: User was reloaded from a user provider. {"username":"teacher@teacher.teacher","provider":"Biz\\User\\UserProvider"} []
[2018-04-14 21:45:54] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "activity not found" at /var/www/html/src/AppBundle/Listener/ExceptionListener.php line 98 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): activity not found at /var/www/html/src/AppBundle/Listener/ExceptionListener.php:98, Codeages\\Biz\\Framework\\Service\\Exception\\NotFoundException(code: 0): activity not found at /var/www/html/src/Biz/BaseService.php:123)"} []
[2018-04-14 21:45:54] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-14 21:49:28] request.INFO: Matched route "user_show". {"route_parameters":{"_controller":"AppBundle\\Controller\\UserController::showAction","_permission":[],"id":"21","_route":"user_show"},"request_uri":"http://192.168.43.215/user/21"} []
[2018-04-14 21:49:28] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-14 21:49:28] security.DEBUG: User was reloaded from a user provider. {"username":"admin@admin.admin","provider":"Biz\\User\\UserProvider"} []
[2018-04-14 21:49:28] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Not Found" at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 251 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Not Found at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:251)"} []
[2018-04-14 21:49:28] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-14 21:51:34] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /course/1/"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /course/1/\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-14 21:51:43] request.INFO: Matched route "course_task_show". {"route_parameters":{"_controller":"AppBundle\\Controller\\TaskController::showAction","_permission":[],"courseId":"1","id":"1","_route":"course_task_show"},"request_uri":"http://127.0.0.1/course/1/task/1/show"} []
[2018-04-14 21:51:43] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-14 21:51:43] security.DEBUG: User was reloaded from a user provider. {"username":"teacher@teacher.teacher","provider":"Biz\\User\\UserProvider"} []
[2018-04-14 21:51:43] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "task not found #1" at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 251 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): task not found #1 at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:251)"} []
[2018-04-14 21:51:43] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-14 21:56:13] request.INFO: Matched route "uploadfile_upload". {"route_parameters":{"_controller":"AppBundle\\Controller\\UploadFileController::uploadAction","_route":"uploadfile_upload","_permission":[]},"request_uri":"http://127.0.0.1/uploadfile/upload?bucket=private&convertHash=ch-materiallib%2F3%2F2018414095545-55gha6.png&convertStatus=none&createdTime=1523714145&createdUserId=3&etag=&ext=png&fileName=%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-14%20%E4%B8%8A%E5%8D%889.23.16.png&fileSize=18361&filename=%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-14%20%E4%B8%8A%E5%8D%889.23.16.png&globalId=0&hash=cmd5%7Cdddb2c835d28cf6798b5efb83e073087&hashId=materiallib%2F3%2F2018414095545-55gha6.png&id=5&length=0&status=uploading&storage=local&targetId=3&targetType=materiallib&type=image&updatedTime=1523714145&updatedUserId=3&userId=3"} []
[2018-04-14 21:56:13] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-14 21:56:13] security.DEBUG: User was reloaded from a user provider. {"username":"teacher@teacher.teacher","provider":"Biz\\User\\UserProvider"} []
[2018-04-14 21:56:13] request.CRITICAL: Uncaught PHP Exception Codeages\Biz\Framework\Service\Exception\ServiceException: "该文件格式，不允许上传。" at /var/www/html/src/Biz/BaseService.php line 133 {"exception":"[object] (Codeages\\Biz\\Framework\\Service\\Exception\\ServiceException(code: 0): 该文件格式，不允许上传。 at /var/www/html/src/Biz/BaseService.php:133)"} []
[2018-04-14 21:56:13] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-14 22:11:02] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /course/1/activity/1"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /course/1/activity/1\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-14 22:17:48] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /admin/admin"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /admin/admin\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-14 23:29:15] request.INFO: Matched route "register_submited". {"route_parameters":{"_controller":"AppBundle\\Controller\\RegisterController::submitedAction","_permission":[],"id":"337","hash":"3247055211e92b8c6471c0b1dfc149c9","_route":"register_submited"},"request_uri":"http://127.0.0.1/register/submited/337/3247055211e92b8c6471c0b1dfc149c9?goto=%2Fapp.php"} []
[2018-04-14 23:29:15] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-14 23:29:16] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Not Found" at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 251 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Not Found at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:251)"} []
[2018-04-14 23:29:33] request.INFO: Matched route "register_submited". {"route_parameters":{"_controller":"AppBundle\\Controller\\RegisterController::submitedAction","_permission":[],"id":"337","hash":"3247055211e92b8c6471c0b1dfc149c9","_route":"register_submited"},"request_uri":"http://127.0.0.1/register/submited/337/3247055211e92b8c6471c0b1dfc149c9?goto=%2Fapp.php"} []
[2018-04-14 23:29:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-14 23:29:33] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Not Found" at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 251 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Not Found at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:251)"} []
[2018-04-14 23:32:57] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /register/submited/24/c8fff3be8d849140e24c2c08b45bce98%3Fgoto%3Dhttp%253A//127.0.0.1/page/aboutus"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /register/submited/24/c8fff3be8d849140e24c2c08b45bce98%3Fgoto%3Dhttp%253A//127.0.0.1/page/aboutus\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-14 23:38:44] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /register/submited/24/c8fff3be8d849140e24c2c08b45bce98%3Fgoto%3Dhttp%253A//127.0.0.1/page/aboutus" (from "http://127.0.0.1/register?goto=http%3A//127.0.0.1/page/aboutus")" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /register/submited/24/c8fff3be8d849140e24c2c08b45bce98%3Fgoto%3Dhttp%253A//127.0.0.1/page/aboutus\" (from \"http://127.0.0.1/register?goto=http%3A//127.0.0.1/page/aboutus\") at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-14 23:44:34] request.INFO: Matched route "register_submited". {"route_parameters":{"_controller":"AppBundle\\Controller\\RegisterController::submitedAction","_permission":[],"id":"337","hash":"3247055211e92b8c6471c0b1dfc149c9","_route":"register_submited"},"request_uri":"http://127.0.0.1/register/submited/337/3247055211e92b8c6471c0b1dfc149c9"} []
[2018-04-14 23:44:34] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-14 23:44:34] security.DEBUG: User was reloaded from a user provider. {"username":"admin@admin.admin","provider":"Biz\\User\\UserProvider"} []
[2018-04-14 23:44:34] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Not Found" at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 251 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Not Found at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:251)"} []
[2018-04-14 23:44:34] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-14 23:45:37] request.INFO: Matched route "register_submited". {"route_parameters":{"_controller":"AppBundle\\Controller\\RegisterController::submitedAction","_permission":[],"id":"337","hash":"3247055211e92b8c6471c0b1dfc149c9","_route":"register_submited"},"request_uri":"http://127.0.0.1/register/submited/337/3247055211e92b8c6471c0b1dfc149c9"} []
[2018-04-14 23:45:37] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-14 23:45:37] security.DEBUG: User was reloaded from a user provider. {"username":"admin@admin.admin","provider":"Biz\\User\\UserProvider"} []
[2018-04-14 23:45:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Not Found" at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 251 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Not Found at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:251)"} []
[2018-04-14 23:45:38] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-15 00:03:17] request.INFO: Matched route "admin_setting_ip_blacklist". {"route_parameters":{"_controller":"AppBundle\\Controller\\Admin\\SettingController::ipBlacklistAction","_route":"admin_setting_ip_blacklist","_permission":["admin_setting_ip_blacklist_manage"]},"request_uri":"http://192.168.43.215/admin/setting/ip-blacklist"} []
[2018-04-15 00:03:17] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-15 00:03:17] security.DEBUG: User was reloaded from a user provider. {"username":"hzgg@yls.lc","provider":"Biz\\User\\UserProvider"} []
[2018-04-15 00:03:17] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2018-04-15 00:03:17] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php:119, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2018-04-15 00:03:18] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-15 00:16:35] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check","_permission":[]},"request_uri":"http://127.0.0.1/login_check"} []
[2018-04-15 00:16:35] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-15 00:16:35] request.WARNING: Unable to look for the controller as the "_controller" parameter is missing. [] []
[2018-04-15 00:16:35] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Unable to find the controller for path "/login_check". The route is wrongly configured." at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 133 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Unable to find the controller for path \"/login_check\". The route is wrongly configured. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:133)"} []
[2018-04-15 00:17:20] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check","_permission":[]},"request_uri":"http://127.0.0.1/login_check"} []
[2018-04-15 00:17:20] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-15 00:17:20] request.WARNING: Unable to look for the controller as the "_controller" parameter is missing. [] []
[2018-04-15 00:17:20] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Unable to find the controller for path "/login_check". The route is wrongly configured." at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 133 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Unable to find the controller for path \"/login_check\". The route is wrongly configured. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:133)"} []
[2018-04-15 00:18:15] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check","_permission":[]},"request_uri":"http://127.0.0.1/login_check"} []
[2018-04-15 00:18:15] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-15 00:18:15] request.WARNING: Unable to look for the controller as the "_controller" parameter is missing. [] []
[2018-04-15 00:18:15] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Unable to find the controller for path "/login_check". The route is wrongly configured." at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 133 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Unable to find the controller for path \"/login_check\". The route is wrongly configured. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:133)"} []
[2018-04-15 00:19:14] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check","_permission":[]},"request_uri":"http://127.0.0.1/login_check"} []
[2018-04-15 00:19:14] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-15 00:19:14] security.DEBUG: User was reloaded from a user provider. {"username":"admin@admin.admin","provider":"Biz\\User\\UserProvider"} []
[2018-04-15 00:19:14] request.WARNING: Unable to look for the controller as the "_controller" parameter is missing. [] []
[2018-04-15 00:19:14] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Unable to find the controller for path "/login_check". The route is wrongly configured." at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 133 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Unable to find the controller for path \"/login_check\". The route is wrongly configured. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:133)"} []
[2018-04-15 00:19:15] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-15 00:30:43] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /web/files//.928e14c9854929ed80a1be176de90b9b.php"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /web/files//.928e14c9854929ed80a1be176de90b9b.php\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-15 00:30:52] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /web/files//.928e14c9854929ed80a1be176de90b9b.php"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /web/files//.928e14c9854929ed80a1be176de90b9b.php\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-15 00:31:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /web/files//.928e14c9854929ed80a1be176de90b9b.php"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /web/files//.928e14c9854929ed80a1be176de90b9b.php\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-15 00:31:10] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /web/files//.928e14c9854929ed80a1be176de90b9b.php"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /web/files//.928e14c9854929ed80a1be176de90b9b.php\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-15 00:45:04] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "您的IP已被列入黑名单，访问被拒绝，如有疑问请联系管理员！" at /var/www/html/src/AppBundle/Listener/ExceptionListener.php line 95 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): 您的IP已被列入黑名单，访问被拒绝，如有疑问请联系管理员！ at /var/www/html/src/AppBundle/Listener/ExceptionListener.php:95, Codeages\\Biz\\Framework\\Service\\Exception\\AccessDeniedException(code: 0): 您的IP已被列入黑名单，访问被拒绝，如有疑问请联系管理员！ at /var/www/html/src/AppBundle/Listener/KernelRequestListener.php:40)"} []
[2018-04-15 00:54:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /admin//setting/user-center"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /admin//setting/user-center\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-15 00:55:22] request.INFO: Matched route "admin_course_set". {"route_parameters":{"_controller":"AppBundle\\Controller\\Admin\\CourseSetController::indexAction","filter":"normal","_permission":["admin_course_manage"],"_route":"admin_course_set"},"request_uri":"http://192.168.43.215/admin/course_set/normal/index"} []
[2018-04-15 00:55:22] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2018-04-15 00:55:22] security.DEBUG: User was reloaded from a user provider. {"username":"teacher@teacher.teacher","provider":"Biz\\User\\UserProvider"} []
[2018-04-15 00:55:22] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2018-04-15 00:55:22] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php:119, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2018-04-15 00:55:22] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-04-15 00:59:46] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /admin//setting/user-center"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /admin//setting/user-center\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-15 01:00:33] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET //admin/setting/user-center"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET //admin/setting/user-center\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-15 01:23:30] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /admin/reward_point/exchange/export"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /admin/reward_point/exchange/export\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-15 01:23:33] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /admin/reward_point/exchange/"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /admin/reward_point/exchange/\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-15 01:23:36] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /admin/reward_point/"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /admin/reward_point/\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-15 01:27:14] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "您的IP已被列入黑名单，访问被拒绝，如有疑问请联系管理员！" at /var/www/html/src/AppBundle/Listener/ExceptionListener.php line 95 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): 您的IP已被列入黑名单，访问被拒绝，如有疑问请联系管理员！ at /var/www/html/src/AppBundle/Listener/ExceptionListener.php:95, Codeages\\Biz\\Framework\\Service\\Exception\\AccessDeniedException(code: 0): 您的IP已被列入黑名单，访问被拒绝，如有疑问请联系管理员！ at /var/www/html/src/AppBundle/Listener/KernelRequestListener.php:40)"} []
[2018-04-15 01:32:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "您的IP已被列入黑名单，访问被拒绝，如有疑问请联系管理员！" at /var/www/html/src/AppBundle/Listener/ExceptionListener.php line 95 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): 您的IP已被列入黑名单，访问被拒绝，如有疑问请联系管理员！ at /var/www/html/src/AppBundle/Listener/ExceptionListener.php:95, Codeages\\Biz\\Framework\\Service\\Exception\\AccessDeniedException(code: 0): 您的IP已被列入黑名单，访问被拒绝，如有疑问请联系管理员！ at /var/www/html/src/AppBundle/Listener/KernelRequestListener.php:40)"} []
[2018-04-15 01:33:36] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "您的IP已被列入黑名单，访问被拒绝，如有疑问请联系管理员！" at /var/www/html/src/AppBundle/Listener/ExceptionListener.php line 95 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): 您的IP已被列入黑名单，访问被拒绝，如有疑问请联系管理员！ at /var/www/html/src/AppBundle/Listener/ExceptionListener.php:95, Codeages\\Biz\\Framework\\Service\\Exception\\AccessDeniedException(code: 0): 您的IP已被列入黑名单，访问被拒绝，如有疑问请联系管理员！ at /var/www/html/src/AppBundle/Listener/KernelRequestListener.php:40)"} []
[2018-04-15 02:17:57] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check","_permission":[]},"request_uri":"http://127.0.0.1/login_check"} []
[2018-04-15 02:17:57] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-15 02:17:57] request.WARNING: Unable to look for the controller as the "_controller" parameter is missing. [] []
[2018-04-15 02:17:57] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Unable to find the controller for path "/login_check". The route is wrongly configured." at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 133 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Unable to find the controller for path \"/login_check\". The route is wrongly configured. at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:133)"} []
[2018-04-15 15:45:46] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /anon/translations/../aaa/1js"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /anon/translations/../aaa/1js\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-15 15:45:53] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /anon/translations/js../aaa/1js"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /anon/translations/js../aaa/1js\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-15 15:45:57] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /anon/translations/js/aaa/1js"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /anon/translations/js/aaa/1js\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-15 15:55:57] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /anon/translations/jssd/"" at /var/www/html/app/cache/prod/classes.php line 2108 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /anon/translations/jssd/\" at /var/www/html/app/cache/prod/classes.php:2108, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/html/app/cache/prod/appProdProjectContainerUrlMatcher.php:8199)"} []
[2018-04-15 16:11:46] request.INFO: Matched route "jstranslation_js". {"route_parameters":{"_controller":"bazinga.jstranslation.controller:getTranslationsAction","domain":"jssd","_format":"js","_permission":[],"_route":"jstranslation_js"},"request_uri":"http://127.0.0.1/anon/translations/jssd?locales=a%2F..%2F..%2F1.js"} []
[2018-04-15 16:11:46] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "" at /var/www/html/vendor/willdurand/js-translation-bundle/Bazinga/Bundle/JsTranslationBundle/Controller/Controller.php line 112 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0):  at /var/www/html/vendor/willdurand/js-translation-bundle/Bazinga/Bundle/JsTranslationBundle/Controller/Controller.php:112)"} []
[2018-04-15 16:11:54] request.INFO: Matched route "jstranslation_js". {"route_parameters":{"_controller":"bazinga.jstranslation.controller:getTranslationsAction","domain":"jssd","_format":"js","_permission":[],"_route":"jstranslation_js"},"request_uri":"http://127.0.0.1/anon/translations/jssd?locales=a"} []
[2018-04-15 16:11:54] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "" at /var/www/html/vendor/willdurand/js-translation-bundle/Bazinga/Bundle/JsTranslationBundle/Controller/Controller.php line 112 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0):  at /var/www/html/vendor/willdurand/js-translation-bundle/Bazinga/Bundle/JsTranslationBundle/Controller/Controller.php:112)"} []
[2018-08-11 19:23:49] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 19:23:49] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 19:24:39] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 19:24:39] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 19:24:56] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 19:24:56] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 19:25:32] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 19:25:32] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 19:25:46] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 19:25:46] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 19:25:53] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 19:25:53] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 19:26:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 19:26:00] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 19:26:06] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 19:26:06] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 19:26:18] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 19:26:18] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 19:27:28] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 19:27:28] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 21:08:59] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 21:08:59] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 21:09:37] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 21:09:37] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 21:10:28] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 21:10:28] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 21:10:57] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 21:10:57] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 21:12:25] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 21:12:25] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 21:13:31] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 21:13:31] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
[2018-08-11 21:13:33] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2018-08-11 21:13:33] request.CRITICAL: Exception thrown when handling an exception (PDOException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php line 3367) {"exception":"[object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at /app/app/cache/prod/appProdProjectContainer.php:3367)"} []
